openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API documentation for Authentication endpoints
paths:
  /api/maintenance/auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - loginUserName
                - password
              properties:
                loginUserName:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful - returns access token, refresh token and user info
        "401":
          description: Authentication failed
  /api/maintenance/auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token using refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
                - userId
              properties:
                refreshToken:
                  type: string
                  description: The refresh token received during login
                userId:
                  type: number
                  description: The user ID
      responses:
        "200":
          description: New access token and refresh token generated successfully
        "401":
          description: Invalid or expired refresh token
  /api/maintenance/auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout - revoke all refresh tokens (clear everything)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logged out successfully from all devices
        "401":
          description: Authentication failed
