openapi: 3.0.0
info:
  title: Permissions API
  version: 1.0.0
  description: API documentation for Permissions endpoints
paths:
  /api/maintenance/permissions:
    get:
      tags:
        - Permissions
      summary: Get all permissions
      description: Retrieve all available permissions.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Array of permissions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
