openapi: 3.0.0
info:
  title: Role API
  version: 1.0.0
  description: API documentation for Role management endpoints
paths:
  /api/maintenance/roles:
    post:
      tags:
        - Roles
      summary: Create a new role with permissions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - roleName
              properties:
                roleName:
                  type: string
                  example: "Admin"
                  description: Name of the role
                permissions:
                  type: object
                  description: Permissions organized by module with boolean flags.
                  additionalProperties: true
                  example:
                    MAINTENANCE:
                      canViewUser: true
                      canCreateUser: true
                      canEditUser: false
                    CFSAIREXPORT:
                      canViewWarehouseReceipt: true
                      canCreateShipmentForm: true
      responses:
        "201":
          description: Role created successfully
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
    get:
      tags:
        - Roles
      summary: Get all roles
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Array of roles
  /api/maintenance/roles/{roleId}:
    get:
      tags:
        - Roles
      summary: Get role by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Role details
        "404":
          description: Role not found
    put:
      tags:
        - Roles
      summary: Update role
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          required: true
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleName:
                  type: string
      responses:
        "200":
          description: Role updated
    delete:
      tags:
        - Roles
      summary: Delete role
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Role deleted
